# Generated by Django 4.2.6 on 2023-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
