# Generated by Django 4.2.6 on 2023-11-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviive', '0002_contractors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contractors',
        ),
    ]
