# Generated by Django 4.2.6 on 2023-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviive', '0017_remove_renovationprice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovationprice',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
