# Generated by Django 4.2.6 on 2023-11-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviive', '0018_renovationprice_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovationprice',
            name='author',
        ),
    ]
