# Generated by Django 4.2.6 on 2023-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviive', '0021_remove_renovationprice_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovationprice',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
